name: Testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: 1.10.3
          otp-version: 23.x
      - name: Download dependencies
        run: mix deps.get
      - name: Compile
        run: mix compile