name: Validation

on: [push, pull_request]

env:
  MIX_ENV: test

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          elixir-version: 1.10.3
          otp-version: "22.0"
      - run: mix deps.get
      - run: mix compile
      - run: mix format --check-formatted
      - run: mix test