name: Validation

on: [push, pull_request]

env:
  MIX_ENV: test

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "23.0"
          elixir-version: "1.11.4"
      - run: mix format --check-formatted
      - run: mix deps.get
      - run: mix compile
      - run: mix test